name: ligandmpnn 
channels:
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.11
  - cuda=12.1
  - pytorch>=2.2=*cuda*
  - pytorch-cuda=12.1
  - biopython=1.79
  - filelock=3.13.1
  - fsspec=2024.3.1
  - jinja2=3.1.3
  - markupSafe=2.1.5
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy>=1.23
  - prody=2.4.1
  - pyparsing=3.1.1
  - scipy=1.12.0
  - sympy=1.12
  - typing_extensions=4.10.0
  - ml-collections=0.1.1
  - dm-tree=0.1.8
  
  - pip
  - pip:
    - triton==2.2.0
